<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GitHub Actions Workflow</title>
    <style>
        body {
            font-family: 'Arial', 'sans-serif';
            background-color: #f5f5f5;
            color: #333;
            margin: 20px;
        }

        h1 {
            color: #0366d6;
        }

        code {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: 2px 4px;
            color: #333;
            border-radius: 4px;
        }

        pre {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: 10px;
            overflow: auto;
        }

        .container {
            max-width: 800px;
            margin: auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>GitHub Actions Workflow</h1>
        
        <h2>Workflow Configuration</h2>
        <pre>
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        </pre>
    </div>
</body>
</html>
